name: date_time_intervals
description: A Flutter package for getting date and time intervals
version: 0.2.0+0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
