name: date_time_intervals
description: A Flutter package for getting date and time intervals
version: 0.2.1+1

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^1.0.14
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
