name: date_time_intervals
description: A Flutter package for getting date and timer intervals
version: 0.1.4+0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
