// Copyright 2020 LTMM. All rights reserved.
// Uses of this source code is governed by 'The Unlicense' that can be
// found in the LICENSE file.
//
library date_time_intervals;

import 'package:enum_to_string/enum_to_string.dart';

export 'intervals.dart';

enum CalendarDirection { between, sinceEnd, untilEnd }

enum CalendarItem {
  years,
  months,
  days,
  hours,
  minutes,
  seconds,
}

/// Helper function that turns a set of CalendarItem into a string for use as SQL data as a comma seperated string
String calendarItemsAsString(Set<CalendarItem> items) {
  String result = '';
  for (CalendarItem item in items) {
    if (result.length > 0) result += ',';
    result += EnumToString.convertToString(item);
  }
  return result;
}

/// Takes the string generated by [calendarItemsAsString] and creates a [Set<CalendarItem>], the use being
/// the [CalendarItem] can be saved then read from SQL database
Set<CalendarItem> calendarItemsFrom({String string}) {
  Set<CalendarItem> result = Set();
  CalendarItem.values.forEach((element) {
    final key = EnumToString.convertToString(element).toLowerCase();
    if (string.toLowerCase().contains(key)) result.add(element);
  });
  return result;
}
